- org: https://www.coursera.org/learn/project-planning/home/welcome
  role: Initiating and Planning Projects
  location: Online
  when: Jan 2017 - March 2017

- org: https://www.coursera.org/learn/schedule-projects/home/welcome
  role: Budgeting and Scheduling Projects
  location: Online
  when: May 2017 - Aug 2017

- org: https://www.coursera.org/learn/project-risk-management/home/welcome
  role: Managing Project Risks and Changes
  location: Online
  when: Sep 2017 - Nov 2017

- org:  Online Berkeley course https://class.coursera.org/saas
  role: Software as a service (SAAS)
  location: Online
  when: Jan 2012 - Apr 2012

- org:  Online Stanford course https://class.coursera.org/gametheory-2012-002/class
  role: Game theory
  location: Online
  when: Jan 2013 - Feb 2013

- org: Online Princeton course https://class.coursera.org/algs4partI-002/class
  role: Algorithms
  location: Online
  when: Feb 2013 - Mar 2013

- org: Online Princeton course https://class.coursera.org/algs4partII-001/class/index
  role: Algorithms part 2
  location: Online
  when: Apr 2013 - May 2013
